/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseEmpty: typeof import('./src/components/base/BaseEmpty.vue')['default']
    BaseIcon: typeof import('./src/components/base/BaseIcon.vue')['default']
    BaseLoading: typeof import('./src/components/base/BaseLoading.vue')['default']
    ChangeThemeBubble: typeof import('./src/components/business/ChangeThemeBubble.vue')['default']
    IconCustomDarkTheme: typeof import('~icons/custom/dark-theme')['default']
    IconCustomLightTheme: typeof import('~icons/custom/light-theme')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanBarrage: typeof import('vant/es')['Barrage']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanRollingText: typeof import('vant/es')['RollingText']
    VanSpace: typeof import('vant/es')['Space']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanWatermark: typeof import('vant/es')['Watermark']
  }
}
